# Generated by Django 5.0.3 on 2024-08-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_http_debug", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debugendpoint",
            name="content_type",
            field=models.CharField(default="text/plain; charset=utf-8", max_length=64),
        ),
        migrations.AddField(
            model_name="debugendpoint",
            name="is_base64",
            field=models.BooleanField(default=False),
        ),
    ]
