# Generated by Django 5.0.3 on 2024-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_http_debug",
            "0002_debugendpoint_content_type_debugendpoint_is_base64",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="query_string",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
