# Generated by Django 5.0.3 on 2024-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_http_debug", "0003_requestlog_query_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="debugendpoint",
            name="logging_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
